### ISSUE TITLE
translation and service initialization

### ISSUE THREAD

**Issue by SinSquare** [vinyvicente/silex-knp-paginator#3]
The way you initialize the provider gave me a hard time today.
Because you set the locale parameter, if the PaginatorProvider is initialized after the TranslationServiceProvider it messes up the locale configuration.

The solution would be that you do not register these providers but you throw an exception if the required services are not registered(like in the RememberMeServiceProvider)

`
if (!isset($app['security.token_storage'])) {
    throw new \LogicException('You must register the SecurityServiceProvider to use the RememberMeServiceProvider');
}
`

**Comment by vinyvicente** [comment]
Done.

Thanks, @hkdobrev
